/* Home.js */
import React, { useEffect, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';
import { db } from '../firebaseConfig';
import '../styles/Home.css';
import '../styles/GlobalStyles.css';
import '../styles/App.css';  /* Ensure to import the updated App.css */
import heroIcon from '../assets/hero-icon.png';
import starIcon from '../assets/star-icon.png';
import userIcon from '../assets/user-icon.png';
import blogIcon from '../assets/blog-icon.png';
import faqIcon from '../assets/faq-icon.png';
import testimonialAvatar from '../assets/testimonial-avatar.png';
import { Accordion, AccordionSummary, AccordionDetails, Typography } from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

const Home = () => {
  const [highlightedEssays, setHighlightedEssays] = useState([]);
  const [blogPosts, setBlogPosts] = useState([]);

  useEffect(() => {
    const fetchHighlightedEssays = async () => {
      const querySnapshot = await getDocs(collection(db, 'highlightedEssays'));
      const essays = querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setHighlightedEssays(essays);
    };

    const fetchBlogPosts = async () => {
      const querySnapshot = await getDocs(collection(db, 'blogPosts'));
      const posts = querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setBlogPosts(posts);
    };

    fetchHighlightedEssays();
    fetchBlogPosts();
  }, []);

  const responsive = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 5
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1
    }
  };

  return (
    <div className="home">
      <section className="hero">
        <h1>Revolutionize Your College Applications</h1>
        <p>Stand out with essays that truly reflect your unique story. Our AI generates compelling essays based on your background.</p>
        <button className="cta-button" onClick={() => window.location.href = '/signup'}>Get Started</button>
      </section>

      <section className="comparison">
        <div className="container">
          <h2>Comparison Between GPT-4 and Scam College AI</h2>
          <div className="comparison-content">
            <div className="comparison-item">
              <h3>GPT-4 Essay</h3>
              <p>This is a sample essay generated by GPT-4. It focuses on the user's idea but may lack the unique insights generated by our AI.</p>
            </div>
            <div className="comparison-item">
              <h3>Scam College AI Essay</h3>
              <p>This is a sample essay generated by Scam College AI. It highlights unique aspects of the user's background, making it stand out.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="highlighted-essays">
        <div className="container">
          <h2>Highlighted Essays <img src={starIcon} alt="Highlighted Essays Icon" className="icon" /></h2>
          <Carousel responsive={responsive} infinite={true} autoPlay={true} autoPlaySpeed={3000}>
            {highlightedEssays.map(essay => (
              <div key={essay.id} className="highlighted-essay-item" onClick={() => window.location.href = `/view-essays/${essay.id}`}>
                <h3>{essay.title}</h3>
                <p>{essay.summary}</p>
              </div>
            ))}
          </Carousel>
        </div>
      </section>

      <section className="testimonials">
        <div className="container">
          <h2>What Our Users Say</h2>
          <p>Join millions of students, researchers, and professionals</p>
          <Carousel responsive={responsive} infinite={true} autoPlay={true} autoPlaySpeed={3000}>
            <div className="testimonial-item">
              <p>"I got a full ride to MIT thanks to the incredible essays generated by Scam College."</p>
              <div className="testimonial-user">
                <img src={testimonialAvatar} alt="User Avatar" />
                <p>- John Smith, MIT</p>
              </div>
            </div>
            <div className="testimonial-item">
              <p>"Scam College transformed my college application. The essays were unique and truly reflected my experiences."</p>
              <div className="testimonial-user">
                <img src={testimonialAvatar} alt="User Avatar" />
                <p>- Jane Doe, Harvard University</p>
              </div>
            </div>
          </Carousel>
        </div>
      </section>

      <section className="blog-posts">
        <div className="container">
          <h2>Latest Blog Posts <img src={blogIcon} alt="Blog Icon" className="icon" /></h2>
          <Carousel responsive={responsive} infinite={true} autoPlay={true} autoPlaySpeed={3000}>
            {blogPosts.map(post => (
              <div key={post.id} className="blog-post-item" onClick={() => window.location.href = `/blog/${post.id}`}>
                <h3>{post.title}</h3>
                <p>{post.excerpt}</p>
                <button className="button">Read More</button>
              </div>
            ))}
          </Carousel>
        </div>
      </section>

      <section className="faq">
        <div className="container">
          <h2>FAQ <img src={faqIcon} alt="FAQ Icon" className="icon" /></h2>
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography>What is Scam College?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>Scam College is an AI-based tool that helps you craft unique and compelling college application essays based on your background.</Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography>How does it work?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>Our AI analyzes your background and generates personalized essay prompts that showcase your strengths and experiences.</Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography>Is there a free plan?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>Yes! All users who sign-up get access to 1000 tokens which can be used across all our tools, with certain features locked.</Typography>
            </AccordionDetails>
          </Accordion>
        </div>
      </section>
    </div>
  );
};

export default Home;