import React from 'react';
import '../styles/Home.css';

const Home = () => {
  return (
    <div className="home">
      <section className="hero-section">
        <h1>Revolutionize Your College Applications with Scam College</h1>
        <p>Stand out in the competitive college admissions process with essays that truly reflect your unique story. Our AI generates compelling essays based on your background, making your application unforgettable.</p>
        <button>Get Started</button>
      </section>

      <div className="sections-container">
        <section className="section ai-analysis">
          <h2>AI-Driven Insights</h2>
          <p>Our advanced AI analyzes your background and crafts essays that stand out to admissions officers, inspired by successful essays from the past.</p>
        </section>

        <section className="section personalized-prompts">
          <h2>Personalized Prompts</h2>
          <p>Receive unique essay prompts tailored to your experiences, ensuring your application showcases your strengths and personality.</p>
        </section>

        <section className="section unparalleled-success">
          <h2>Unparalleled Success</h2>
          <p>Join thousands of students who have gained full rides to top universities using our unconventional yet highly effective approach.</p>
        </section>

        <section className="section ethical-edge">
          <h2>Ethical Edge</h2>
          <p>We aim to level the playing field by providing powerful tools to every student, regardless of their background.</p>
        </section>

        <section className="section testimonials">
          <h2>What Our Users Say</h2>
          <div className="testimonial-grid">
            <div className="testimonial-item">
              <p>"Scam College transformed my college application. The essays were unique and truly reflected my experiences."</p>
              <p>- Jane Doe, Harvard University</p>
            </div>
            <div className="testimonial-item">
              <p>"I got a full ride to MIT thanks to the incredible essays generated by Scam College."</p>
              <p>- John Smith, MIT</p>
            </div>
          </div>
        </section>

        <section className="section cta">
          <h2>Ready to Transform Your College Application?</h2>
          <button>Sign Up Today</button>
        </section>
      </div>
    </div>
  );
};

export default Home;